### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by nviospvkuadt** [ankosoftware/ng2-bootstrap-modal#44]
I receive the following error(s) when running Webpack (2.5.1) after adding BootstrapModalModule to app.module.ts. Everything I've read says upgrading to Webpack 2 will resolve this type of error but we're already on this version.

node node_modules/webpack/bin/webpack.js --env.prod
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
    <div #container class="modal fade" style="display:block !important;" role="dialog">
        [WARNING ->]<template #element></template>
    </div>
"): ng:///C:/Projects/Subco/SUBCOROOT-Branches/DEV/Subdirect.Web.Admin/node_modules/ng2-bootstrap-modal/dist/dialog-wrapper.component.d.ts.DialogWrapperComponent.html@2:8
Hash: ddaf8731aaaeae751566627725e4c7bc1b90b868
Version: webpack 2.5.1
Child
    Hash: ddaf8731aaaeae751566
    Time: 51671ms
             Asset     Size  Chunks                    Chunk Names
    main-client.js  1.06 MB       0  [emitted]  [big]  main-client

    ERROR in ./$$_gendir/~/ng2-bootstrap-modal/dist/dialog-holder.component.ngfactory.ts
    Module parse failed: C:\Projects\Subco\SUBCOROOT-Branches\DEV\Subdirect.Web.Admin\$$_gendir\node_modules\ng2-bootstrap-modal\dist\dialog-holder.component.ngfactory.ts Unexpected token (11:34)
    You may need an appropriate loader to handle this file type.
    | import * as i0 from '@angular/core';
    | import * as i1 from 'ng2-bootstrap-modal/dist/dialog-holder.component';
    | const styles_DialogHolderComponent:any[] = ([] as any[]);
    | export const RenderType_DialogHolderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    |     styles:styles_DialogHolderComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts 10:0-113
     @ ./ClientApp/boot.browser.ts

    ERROR in ./$$_gendir/~/ng2-bootstrap-modal/dist/dialog-wrapper.component.ngfactory.ts
    Module parse failed: C:\Projects\Subco\SUBCOROOT-Branches\DEV\Subdirect.Web.Admin\$$_gendir\node_modules\ng2-bootstrap-modal\dist\dialog-wrapper.component.ngfactory.ts Unexpected token (12:35)
    You may need an appropriate loader to handle this file type.
    | import * as i1 from 'ng2-bootstrap-modal/dist/dialog-wrapper.component';
    | import * as i2 from 'ng2-bootstrap-modal/dist/dialog.service';
    | const styles_DialogWrapperComponent:any[] = ([] as any[]);
    | export const RenderType_DialogWrapperComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    |     styles:styles_DialogWrapperComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts 11:0-114
     @ ./ClientApp/boot.browser.ts
Child
    Hash: 627725e4c7bc1b90b868
    Time: 38312ms
             Asset     Size  Chunks                    Chunk Names
    main-server.js  6.14 MB       0  [emitted]  [big]  main-server

    ERROR in ./$$_gendir/~/ng2-bootstrap-modal/dist/dialog-holder.component.ngfactory.ts
    Module parse failed: C:\Projects\Subco\SUBCOROOT-Branches\DEV\Subdirect.Web.Admin\$$_gendir\node_modules\ng2-bootstrap-modal\dist\dialog-holder.component.ngfactory.ts Unexpected token (11:34)
    You may need an appropriate loader to handle this file type.
    | import * as i0 from '@angular/core';
    | import * as i1 from 'ng2-bootstrap-modal/dist/dialog-holder.component';
    | const styles_DialogHolderComponent:any[] = ([] as any[]);
    | export const RenderType_DialogHolderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    |     styles:styles_DialogHolderComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts 10:0-113
     @ ./ClientApp/boot.server.ts

    ERROR in ./$$_gendir/~/ng2-bootstrap-modal/dist/dialog-wrapper.component.ngfactory.ts
    Module parse failed: C:\Projects\Subco\SUBCOROOT-Branches\DEV\Subdirect.Web.Admin\$$_gendir\node_modules\ng2-bootstrap-modal\dist\dialog-wrapper.component.ngfactory.ts Unexpected token (12:35)
    You may need an appropriate loader to handle this file type.
    | import * as i1 from 'ng2-bootstrap-modal/dist/dialog-wrapper.component';
    | import * as i2 from 'ng2-bootstrap-modal/dist/dialog.service';
    | const styles_DialogWrapperComponent:any[] = ([] as any[]);
    | export const RenderType_DialogWrapperComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    |     styles:styles_DialogWrapperComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts 11:0-114
     @ ./ClientApp/boot.server.ts

**Comment by mrjohnr** [comment]
same problem here :(
any fix?  
thanks

**Comment by ndfreeman** [comment]
@mrjohnr Take a look at the solution for this issue - https://github.com/aspnet/JavaScriptServices/issues/1168. In our case, the problem was caused by the typescript loader in webpack. It was only looking in the ClientApp folder, preventing this plugin from transpiling. Removing the "includes: '/ClientApp/'" line fixed it.

**Comment by mrjohnr** [comment]
indeed,that fixed.thanks

**Comment by nviospvkuadt** [comment]
Thankyou everyone for your feedback.
