### ISSUE TITLE
Blank title and message

### ISSUE THREAD

**Issue by AakritiGoyal** [ankosoftware/ng2-bootstrap-modal#52]
I am not able to see the title and message when i try to navigate to a new route. Please help me

**Comment by celsomtrindade** [comment]
Are you sure this is related to `ng2-bootstrap-modal`?

**Comment by AakritiGoyal** [comment]
@celsomtrindade Thanks for your reply... i am not sure about it .. but now i am using ngx-bootstrap-modal and it's working fine
