### ISSUE TITLE
Modal backdrop

### ISSUE THREAD

**Issue by narendra-agashe** [ankosoftware/ng2-bootstrap-modal#8]
This is very helpful for displaying modal popups in angular2 applications. great work!

How can I show static modal backdrop in here? and change the size of the modal popups?

Regards,
Naren

**Comment by bikalay** [comment]
Sorry for delay. I collected feedback and prepared big portion of changes. 
You can set default backdrop color via css
For ex:
```css
.modal {
     backgroundColor: rgba(90,90,90,0.5);
}
```

Or you can set custom backdrop color for each dialog:
```typescript
showAlert() {
    this.dialogService.addDialog(AlertComponent, { message:'Dialog with red backdrop' }, { backdropColor: 'rgba(255, 0, 0, 0.5)' });
}
```
About size.
For bootstrap 3
set style (or use css ) for .modal-dialog
```typescript
@Component({
  selector: 'large-dialog',
  template: `<div class="modal-dialog" style="width: 800px;">
                        <div class="modal-content" >
                                     .....
                  `
```

For bootstrap 4
set style (or use css ) for .modal-content
```typescript
@Component({
  selector: 'large-dialog',
  template: `<div class="modal-dialog" >
                        <div class="modal-content" style="width: 800px;" >
                                     .....
                  `
```

Thank you for your feedback

**Comment by narendra-agashe** [comment]
Fantastic work!

Just one suggestion, can we make modal popup sizes responsive by using bootstrap classes. currently this static width makes it non-responsive. I am still in learning phase for angular 2 so not able to contribute much. 

Thanks,
Naren

**Comment by bikalay** [comment]
@narendra-agashe Yep, you can use bootstrap classes (modal-sm, modal-lg...) or create your own class.
For bootstrap3
```typescript
@Component({
  selector: 'small-dialog',
  template: `<div class="modal-dialog modal-sm" >
                        <div class="modal-content" >
                                     .....
``` 
or some your class
```typescript
@Component({
  selector: 'my-dialog',
  template: `<div class="modal-dialog my-modal" >
                        <div class="modal-content" >
                                     .....
``` 
```less
 .my-modal { width: @my-modal-width1; }
@media (min-width: @screen-md-min) {
  .my-modal { width: @my-modal-width2; }
}
```

**Comment by narendra-agashe** [comment]
Fantastic Work!
everything works.

Thanks a lot.
